name: Discord Notification
on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Webhook Action
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          content: "<@&1482100826154598572>"
          embed-title: "🚀 Neues Release für Twilight Imperium IV!"
          embed-url: "${{ github.event.release.html_url }}"
          embed-description: "**Version:** `${{ github.event.release.tag_name }}`\n\n${{ github.event.release.body }}"
          embed-color: 11027200
          embed-image-url: "https://github.com/Oxx0r/TI4/raw/main/Mods/Images/httpssteamusercontentaakamaihdnetugc9180410353502922996A6B2E95F41F29E3933B3E54DC35A7D201570616.png"
          embed-footer-text: "Release, you say?"
